id = "blueberry-night-theme"
name = "Blueberry Night"
version = "1.0.0"
schema_version = 1
authors = ["rangaNP"]
description = "Meet the Blue!"
repository = "https://github.com/rangaNP/blueberry-night-zed"
